function svm = train_svm(solver, classids, psix)
  global conf model;
  switch model.svm.solver
    case {'sgd', 'sdca'}
      lambda = 1 / (model.svm.C * length(trainingData.imageClasses(trainIndices))) ;
      w = [] ;
      %for ci = 1:length(labels)
      parfor ci = 1:length(trainingData.imageClasses(trainIndices))
        y = 2 * (trainingData.imageClassIds(trainIndices) == ci) - 1 ;
        [w(:,ci) b(ci) info] = ...
           vl_svmtrain(psix(:, trainingData.imageClassIds(trainIndices)), ...
                       y, ...
                       lambda, ...
                       'Solver', model.svm.solver, ...
                       'MaxNumIterations', 50/lambda, ...
                       'BiasMultiplier', model.svm.biasMultiplier, ...
                       'Epsilon', 1e-3);
      end
    case 'liblinear'
      svm = train(trainingData.imageClassIds(trainIndices)', ...
                  sparse(double(psix)),  ...
                  sprintf(' -s 3 -B %f -c %f', ...
                  model.svm.biasMultiplier, model.svm.C), ...
                  'col') ;
      w = svm.w(:,1:end-1)' ;
      b = svm.w(:,end)' ;
  end
  model.b = model.svm.biasMultiplier * b ;
  model.w = w ;
  save(conf.modelFile, 'model') ;
end